### ISSUE TITLE
RPC Error: Invalid argument 0

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/star.market#20]
Hitting this error when swapping star -> WSTR

<img width="1031" alt="Screen Shot 2021-10-25 at 5 07 43 PM" src="https://user-images.githubusercontent.com/5265021/138771288-44762cee-276c-4014-967b-1326e4715a99.png">

**Comment by willbach** [comment]
I'm seeing this too, but it's not preventing me from swapping stars. I'll try to figure out where it's coming from

**Comment by willbach** [comment]
this should be resolved

**Comment by g-a-v-i-n** [comment]
Is it resolved in a branch?

**Comment by willbach** [comment]
it should have been resolved in `ropsten-env`, so it should now be merged. Let me know if it isn't

**Comment by g-a-v-i-n** [comment]
Ok I will try to trigger it
