### ISSUE TITLE
Not using correct ABI?

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/star.market#21]
Getting the following error when connecting to metamask on localhost

```
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

<img width="1038" alt="Screen Shot 2021-10-27 at 11 10 37 AM" src="https://user-images.githubusercontent.com/5265021/139094309-aa8c7bc3-4e86-443c-ac61-564645e3f2d8.png">

**Comment by g-a-v-i-n** [comment]
Seems fine on the deployment, however I cannot access parts of the flow during dev unless I deploy.

**Comment by willbach** [comment]
yeah I fixed this message. What parts of the flow can you not access?

**Comment by g-a-v-i-n** [comment]
I get this message as soon as I connect to metamask in local dev, so anything that involves swapping.
