### ISSUE TITLE
Default gas is not applied to transaction

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/star.market#22]
I'm not 100% sure this is happening, but it doesn't seem like my gas selection makes it into the Metamask stage. This seems to cause the tx to hang.

<img width="359" alt="Screen Shot 2021-10-27 at 11 21 23 AM" src="https://user-images.githubusercontent.com/5265021/139096728-b9d8c513-883c-4868-b719-09d65bcf6379.png">

**Comment by g-a-v-i-n** [comment]
Looks like a default is not set, but the selection does seem to work. However, I have to manually set gas in metamask in the star deposit stage.

**Comment by willbach** [comment]
I'll take a look
