### ISSUE TITLE
Remove obstructive  "please connect a wallet" alert

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/star.market#37]

**Comment by willbach** [comment]
@g-a-v-i-n where does this alert appear? I can't find it when searching for "please connect a wallet" in the code

**Comment by g-a-v-i-n** [comment]
It shows up if you use a browser without the Metamask extension installed.

**Comment by willbach** [comment]
Ok. I'll need to add an infura endpoint in that case and test it out. I wanted to avoid that but I guess there's no way around it.

**Comment by willbach** [comment]
It also looks like the main repo is missing some updates, I'll submit a PR in a minute

**Comment by g-a-v-i-n** [comment]
Ok great. Ideally the wallet check wouldn't happen until the user navigated to `/app`

**Comment by willbach** [comment]
By "some updates" I mean that the app doesn't work right now. I have 30+ files updated that I'll have to test on Ropsten again

**Comment by g-a-v-i-n** [comment]
Hmm that doesn't seem right. Are you talking about #38?

**Comment by willbach** [comment]
Yes, it has a bunch of changes that are not in `master`

**Comment by willbach** [comment]
as in, I was building `master` to run on Ropsten and it wasn't working

**Comment by willbach** [comment]
have you tested it recently?

**Comment by g-a-v-i-n** [comment]
I have not tested on `master` because we are using `app` as the leading edge branch for the app release. Anything pushed to `master` will be built by vercel for production. So it makes sense `master` wouldn't work right now.

**Comment by g-a-v-i-n** [comment]
So I think the base branch for that PR should be `app`. Does that make sense?

**Comment by willbach** [comment]
oh ok, that's the issue. Been too long since I worked on this

**Comment by willbach** [comment]
@g-a-v-i-n I've added a few more updates in [this PR](https://github.com/urbit/starketplace/pull/39), can I merge it into `app`? I can then make a new PR to merge all `app` changes into `master`
